[workspace]
members = ["proto", "x2ssh", "x2ssh-agent"]
default-members = ["x2ssh"]
resolver = "2"

[profile.release-agent]
inherits = "release"
strip = true
lto = true
panic = "abort"
opt-level = "z"
