unstable_features = true

imports_layout = "Vertical"
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
wrap_comments = true
use_field_init_shorthand = true
style_edition = "2024"
edition = "2024"
single_line_let_else_max_width = 0
overflow_delimited_expr = true
normalize_comments = true
newline_style = "Unix"
