[project]
name = "x2ssh-e2e"
version = "0.1.0"
description = "End-to-end tests for x2ssh"
requires-python = ">=3.12"
dependencies = [
    "pysocks>=1.7.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "testcontainers>=4.14.1",
]
